# .github/workflows/scheduled-calls.yml
name: Trigger notification call on a CRON Schedule

on:
  workflow_dispatch:
  schedule:
    # Runs "everyday at 5:02pm" (see https://crontab.guru)
    - cron: '02 17 * * *'

jobs:
  notify:
    name: Trigger Notification Call
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cURL request
        run: curl -X GET "${{ secrets.BASE_URL }}/notify?user=${{ secrets.USER_EMAIL }}&token=${{ secrets.USER_TOKEN }}"
      - uses: gautamkrishnar/keepalive-workflow@master # step to keep alive the cron action