# .github/workflows/scheduled-calls.yml
name: Trigger notification call on a CRON Schedule

on:
  schedule:
    # Runs "everyday at 5:02pm" (see https://crontab.guru)
    - cron: '02 17 * * *'

jobs:
  notify:
    name: Trigger Notification Call
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cURL request
        run: curl -X GET "${{ secrets.BASE_URL }}/notify?user=${{ secrets.USER_EMAIL }}&token=${{ secrets.USER_TOKEN }}"

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1 # step to keep alive the cron action